### ISSUE TITLE
В функции "ТелоОтвета" модуль КлиентHTTPКлиентСервер нет проверки на пустое тело ответа.

### ISSUE THREAD

**Issue by DenisMonakhov** [SpaceHead1C/1c_http#66]
https://github.com/SpaceHead1C/1c_http/blob/eeb7ac6ed4b4dd4964faed6014dd1780b6696fc9/src/v1/CommonModules/%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82HTTP%D0%9A%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%A1%D0%B5%D1%80%D0%B2%D0%B5%D1%80/Ext/Module.bsl#L1674

Бывает так, что 200-ый ответ возвращает JSON в теле. Т.е. хочется выполнять запрос с настройкой "ТелоОтветаКакJSON". Но 404 ответ того же запроса возвращает пустое тело. Предлагаю в функции "ТелоОтвета" делать проверку на пустое тело ответа и только в случае не пустого тела пытаться его обработать, в противном случае вываливается ошибка "Недопустимое состояние потока записи JSON".

**Comment by SpaceHead1C** [comment]
Справедливо. Взял в работу

**Comment by SpaceHead1C** [comment]
Исправил. В версиях 1.8.0 и 2.2.0
